#
# @file stand_emulator/Dockerfile
# @author Pavan Dayal
#

# arguments
ARG STAND_EMU
ARG VERSION
ARG BASE_IMG

# base
FROM $BASE_IMG
LABEL \
    Maintainer="admin@liquidrocketry.com" \
    Name="$STAND_EMU" \
    Version="$VERSION"

# dependencies

# build
